# Check exported Hugging Face dataset

Use this notebook after running the pipeline to inspect the saved `hf_dataset` folder.

In [3]:
from pathlib import Path

import pandas as pd
from datasets import DatasetDict, load_from_disk

# Update this path if your dataset lives somewhere else.
DATASET_DIR = Path("../data/processed/hf_dataset")
# Example for a single processed video:
# DATASET_DIR = Path("../data/processed/VIDEO_ID/hf_dataset")

print(f"Checking: {DATASET_DIR.resolve()}")
print("Exists:", DATASET_DIR.exists())

c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Checking: C:\Users\nextt\Desktop\yaswanth_v\capstone-project\data\processed\hf_dataset
Exists: True

In [4]:
dataset = load_from_disk(str(DATASET_DIR))
dataset

DatasetDict({
    train: Dataset({
        features: ['audio', 'sentence', 'text', 'duration_s', 'video_id', 'start', 'end'],
        num_rows: 257
    })
    validation: Dataset({
        features: ['audio', 'sentence', 'text', 'duration_s', 'video_id', 'start', 'end'],
        num_rows: 28
    })
})

In [5]:
if isinstance(dataset, DatasetDict):
    split_names = list(dataset.keys())
else:
    split_names = ["train"]
    dataset = DatasetDict({"train": dataset})

summary_rows = []
for split_name in split_names:
    split_ds = dataset[split_name]
    summary_rows.append(
        {
            "split": split_name,
            "rows": len(split_ds),
            "columns": ", ".join(split_ds.column_names),
            "features": str(split_ds.features),
        }
    )

pd.DataFrame(summary_rows)

,split,rows,columns,features
0,train,257,"audio, sentence, text, duration_s, video_id, s...","{'audio': Audio(sampling_rate=16000, decode=Tr..."
1,validation,28,"audio, sentence, text, duration_s, video_id, s...","{'audio': Audio(sampling_rate=16000, decode=Tr..."

In [6]:
preview_split = split_names[0]
preview_columns = [
    col for col in ["text", "sentence", "duration_s", "video_id", "start", "end"]
    if col in dataset[preview_split].column_names
]

dataset[preview_split].select(range(min(5, len(dataset[preview_split])))).to_pandas()[preview_columns]

,text,sentence,duration_s,video_id,start,end
0,varaku unna [news] ayitē ivi [news] lōki,varaku unna [news] ayitē ivi [news] lōki,1.67,ve8XqZ3bRcM,00:00:07.680,00:00:09.350
1,[display] mottaṁ mīku [flat] kanipistadi.,[display] mottaṁ mīku [flat] kanipistadi.,2.31,ve8XqZ3bRcM,00:02:45.760,00:02:48.070
2,mana chānal ni sabskraib cēsukoni phālō,mana chānal ni sabskraib cēsukoni phālō,1.27,ve8XqZ3bRcM,00:09:03.120,00:09:04.389
3,[next] [news] lōki veḷḷē muṁdu,[next] [news] lōki veḷḷē muṁdu,0.87,ve8XqZ3bRcM,00:06:39.039,00:06:39.909
4,[refrigerator] [double] [door] [refrigerator],[refrigerator] [double] [door] [refrigerator],1.75,ve8XqZ3bRcM,00:01:46.399,00:01:48.149

In [7]:
dataset = dataset.with_format("torch")

sample = dataset[preview_split][0]

print("Available keys:", list(sample.keys()))
print("\nText:", sample.get("text"))
print("Sentence:", sample.get("sentence"))
print("Duration:", sample.get("duration_s"))
print("Video ID:", sample.get("video_id"))
print("Start:", sample.get("start"))
print("End:", sample.get("end"))

sample["audio"]

RuntimeError: Could not load libtorchcodec. Likely causes:
          1. FFmpeg is not properly installed in your environment. We support
             versions 4, 5, 6, 7, and 8, and we attempt to load libtorchcodec
             for each of those versions. Errors for versions not installed on
             your system are expected; only the error for your installed FFmpeg
             version is relevant. On Windows, ensure you've installed the
             "full-shared" version which ships DLLs.
          2. The PyTorch version (2.11.0+cpu) is not compatible with
             this version of TorchCodec. Refer to the version compatibility
             table:
             https://github.com/pytorch/torchcodec?tab=readme-ov-file#installing-torchcodec.
          3. Another runtime dependency; see exceptions below.

        The following exceptions were raised as we tried to load libtorchcodec:

[start of libtorchcodec loading traceback]
FFmpeg version 8:
Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1503, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core8.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 93, in load_torchcodec_shared_libraries
    torch.ops.load_library(core_library_path)
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1505, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core8.dll

FFmpeg version 7:
Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1503, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core7.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 93, in load_torchcodec_shared_libraries
    torch.ops.load_library(core_library_path)
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1505, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core7.dll

FFmpeg version 6:
Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1503, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core6.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 93, in load_torchcodec_shared_libraries
    torch.ops.load_library(core_library_path)
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1505, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core6.dll

FFmpeg version 5:
Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1503, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core5.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 93, in load_torchcodec_shared_libraries
    torch.ops.load_library(core_library_path)
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1505, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core5.dll

FFmpeg version 4:
Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1503, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core4.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 93, in load_torchcodec_shared_libraries
    torch.ops.load_library(core_library_path)
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1505, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core4.dll
[end of libtorchcodec loading traceback].

In [8]:
sample = dataset[preview_split][0]
print(type(sample["audio"]))
print(sample["audio"])

RuntimeError: Could not load libtorchcodec. Likely causes:
          1. FFmpeg is not properly installed in your environment. We support
             versions 4, 5, 6, 7, and 8, and we attempt to load libtorchcodec
             for each of those versions. Errors for versions not installed on
             your system are expected; only the error for your installed FFmpeg
             version is relevant. On Windows, ensure you've installed the
             "full-shared" version which ships DLLs.
          2. The PyTorch version (2.11.0+cpu) is not compatible with
             this version of TorchCodec. Refer to the version compatibility
             table:
             https://github.com/pytorch/torchcodec?tab=readme-ov-file#installing-torchcodec.
          3. Another runtime dependency; see exceptions below.

        The following exceptions were raised as we tried to load libtorchcodec:

[start of libtorchcodec loading traceback]
FFmpeg version 8:
Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1503, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core8.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 93, in load_torchcodec_shared_libraries
    torch.ops.load_library(core_library_path)
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1505, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core8.dll

FFmpeg version 7:
Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1503, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core7.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 93, in load_torchcodec_shared_libraries
    torch.ops.load_library(core_library_path)
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1505, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core7.dll

FFmpeg version 6:
Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1503, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core6.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 93, in load_torchcodec_shared_libraries
    torch.ops.load_library(core_library_path)
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1505, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core6.dll

FFmpeg version 5:
Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1503, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core5.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 93, in load_torchcodec_shared_libraries
    torch.ops.load_library(core_library_path)
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1505, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core5.dll

FFmpeg version 4:
Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1503, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core4.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\_internally_replaced_utils.py", line 93, in load_torchcodec_shared_libraries
    torch.ops.load_library(core_library_path)
  File "c:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torch\_ops.py", line 1505, in load_library
    raise OSError(f"Could not load this library: {path}") from e
OSError: Could not load this library: C:\Users\nextt\Desktop\yaswanth_v\capstone-project\myenv\Lib\site-packages\torchcodec\libtorchcodec_core4.dll
[end of libtorchcodec loading traceback].

In [9]:
from datasets import Audio

dataset = dataset.cast_column("audio", Audio(decode=False))

In [10]:
sample = dataset[preview_split][0]

print(sample.keys())
print(sample["text"])
print(sample["sentence"])
print(sample["duration_s"])
print(sample["video_id"])
print(sample["start"])
print(sample["end"])

print(sample["audio"])   # SAFE (no crash)

dict_keys(['audio', 'sentence', 'text', 'duration_s', 'video_id', 'start', 'end'])
varaku unna [news] ayitē ivi [news] lōki
varaku unna [news] ayitē ivi [news] lōki
tensor(1.6700)
ve8XqZ3bRcM
00:00:07.680
00:00:09.350